name: "work please"
clusterId: clqr4b0ox
command: python mnist.py
container: tensorflow/tensorflow:1.13.1-gpu-py3
datasetAwsAccessKeyId: null
datasetAwsSecretAccessKey: null
datasetEtag: null
datasetName: null
datasetUri: null
datasetVersionId: null
experimentEnv:
  EPOCHS_EVAL: 5
  EVAL_SECS: 10
  MAX_STEPS: 1000
  TRAIN_EPOCHS: 10
isPreemptible: false
machineType: p2.xlarge
projectId: prda8mhcq
tensorboard: false
vpc: true
workspace: https://github.com/Paperspace/mnist-sample.git
