version: 2
workflows:
  classify-pytorch:
    steps:
      - name: torch-fog
        command: experiment.run_single_node
        paramsFile: .ps_project/classify-singlenode.yaml
    triggers:
        branches:
            only: .*
        tags:
            only:
            - v.*
            - latest
